QT-5977 : changes in getting turn config
joshtechnologygroup/testrtc pull request #1
Opened 2022-12-23 14:23 UTC by tarunrao8

**Description**
Get TestRTC turn config form quicktest

**Purpose**

2022-12-24 16:39 UTC, rajatkumar79 requested changes

2022-12-24 16:39 UTC, rajatkumar79 commented on src/js/call.js
> +      };
Check if this is working?

2022-12-24 16:39 UTC, rajatkumar79 commented on src/js/call.js
> -    Call.fetchTurnConfig_(function(response) {
Can't we just use this function?

2022-12-27 11:01 UTC, rajatkumar79 approved these changes

2022-12-27 11:15 UTC, chahat-arora approved these changes

2022-12-27 11:16 UTC, merged